[phases.setup]
nixPkgs = ["nodejs_20", "docker"]

[phases.install]
cmds = ["npm install", "cd client && npm install"]

[phases.build]
cmds = ["cd client && npm run build", "npm run build"]

[start]
cmd = "npm run start:production"
